name: Free Tier CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 0'  # Weekly Sunday 2 AM

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Basic validation
        run: |
          echo "Repository: ${{ github.repository }}"
          ls -la
          echo "✅ Basic checks passed"